#
# Serverless configuration reference:
#
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#
frameworkVersion: ">= 2.0.0"

service: hello-http

provider:
  name: aws
  region: us-east-1
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          # TODO Change to use path parameter
          path: hello
          method: get
  # TODO Set up the new function here to handle HTTP POST event

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      # Comment out if you want to deploy to AWS instead of LocalStack
      - dev
